/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef message_CONSTANTS_H
#define message_CONSTANTS_H

#include "message_types.h"

namespace squirrel { namespace protocol {

class messageConstants {
 public:
  messageConstants();

};

extern const messageConstants g_message_constants;

}} // namespace

#endif
