/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "message_constants.h"

namespace squirrel { namespace protocol {

const messageConstants g_message_constants;

messageConstants::messageConstants() {
}

}} // namespace

