/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_list_message_CONSTANTS_H
#define protocol_list_message_CONSTANTS_H

#include "protocol_list_message_types.h"

namespace squirrel { namespace protocol {

class protocol_list_messageConstants {
 public:
  protocol_list_messageConstants();

};

extern const protocol_list_messageConstants g_protocol_list_message_constants;

}} // namespace

#endif
