/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_number_message_CONSTANTS_H
#define protocol_number_message_CONSTANTS_H

#include "protocol_number_message_types.h"

namespace squirrel { namespace protocol {

class protocol_number_messageConstants {
 public:
  protocol_number_messageConstants();

};

extern const protocol_number_messageConstants g_protocol_number_message_constants;

}} // namespace

#endif
