/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_keyvalue_message_constants.h"

namespace squirrel { namespace protocol {

const protocol_keyvalue_messageConstants g_protocol_keyvalue_message_constants;

protocol_keyvalue_messageConstants::protocol_keyvalue_messageConstants() {
}

}} // namespace

