/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_map_message_CONSTANTS_H
#define protocol_map_message_CONSTANTS_H

#include "protocol_map_message_types.h"

namespace squirrel { namespace protocol {

class protocol_map_messageConstants {
 public:
  protocol_map_messageConstants();

};

extern const protocol_map_messageConstants g_protocol_map_message_constants;

}} // namespace

#endif
