/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_number_message_TYPES_H
#define protocol_number_message_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace squirrel { namespace protocol {

struct NumberRequestType {
  enum type {
    NUMBER_REQUEST_TYPE_INC = 0,
    NUMBER_REQUEST_TYPE_DEC = 1,
    NUMBER_REQUEST_TYPE_RESET = 2,
    NUMBER_REQUEST_TYPE_DELETE = 3,
    NUMBER_REQUEST_TYPE_MAX = 4
  };
};

extern const std::map<int, const char*> _NumberRequestType_VALUES_TO_NAMES;

struct NumberResponseType {
  enum type {
    NUMBER_RESPONSE_TYPE_SUCCESS = 0,
    NUMBER_RESPONSE_TYPE_KEY_NOT_EXIST = 1,
    NUMBER_RESPONSE_TYPE_DISCONNECTED = 2,
    NUMBER_RESPONSE_TYPE_UNKNOWN = 3,
    NUMBER_RESPONSE_TYPE_MAX = 4
  };
};

extern const std::map<int, const char*> _NumberResponseType_VALUES_TO_NAMES;

typedef struct _NumberRequest__isset {
  _NumberRequest__isset() : increment_(false) {}
  bool increment_;
} _NumberRequest__isset;

class NumberRequest {
 public:

  static const char* ascii_fingerprint; // = "8A168E64138582CD39890B77E0F15FF4";
  static const uint8_t binary_fingerprint[16]; // = {0x8A,0x16,0x8E,0x64,0x13,0x85,0x82,0xCD,0x39,0x89,0x0B,0x77,0xE0,0xF1,0x5F,0xF4};

  NumberRequest() : type_((NumberRequestType::type)0), key_(""), increment_("") {
  }

  virtual ~NumberRequest() throw() {}

  NumberRequestType::type type_;
  std::string key_;
  std::string increment_;

  _NumberRequest__isset __isset;

  void __set_type_(const NumberRequestType::type val) {
    type_ = val;
  }

  void __set_key_(const std::string& val) {
    key_ = val;
  }

  void __set_increment_(const std::string& val) {
    increment_ = val;
    __isset.increment_ = true;
  }

  bool operator == (const NumberRequest & rhs) const
  {
    if (!(type_ == rhs.type_))
      return false;
    if (!(key_ == rhs.key_))
      return false;
    if (__isset.increment_ != rhs.__isset.increment_)
      return false;
    else if (__isset.increment_ && !(increment_ == rhs.increment_))
      return false;
    return true;
  }
  bool operator != (const NumberRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NumberRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NumberResponse__isset {
  _NumberResponse__isset() : value_(false) {}
  bool value_;
} _NumberResponse__isset;

class NumberResponse {
 public:

  static const char* ascii_fingerprint; // = "24652790C81ECE22B629CB60A19F1E93";
  static const uint8_t binary_fingerprint[16]; // = {0x24,0x65,0x27,0x90,0xC8,0x1E,0xCE,0x22,0xB6,0x29,0xCB,0x60,0xA1,0x9F,0x1E,0x93};

  NumberResponse() : result_((NumberResponseType::type)0), value_("") {
  }

  virtual ~NumberResponse() throw() {}

  NumberResponseType::type result_;
  std::string value_;

  _NumberResponse__isset __isset;

  void __set_result_(const NumberResponseType::type val) {
    result_ = val;
  }

  void __set_value_(const std::string& val) {
    value_ = val;
    __isset.value_ = true;
  }

  bool operator == (const NumberResponse & rhs) const
  {
    if (!(result_ == rhs.result_))
      return false;
    if (__isset.value_ != rhs.__isset.value_)
      return false;
    else if (__isset.value_ && !(value_ == rhs.value_))
      return false;
    return true;
  }
  bool operator != (const NumberResponse &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NumberResponse & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

}} // namespace

#endif
