/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_map_message_constants.h"

namespace squirrel { namespace protocol {

const protocol_map_messageConstants g_protocol_map_message_constants;

protocol_map_messageConstants::protocol_map_messageConstants() {
}

}} // namespace

