/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_number_message_constants.h"

namespace squirrel { namespace protocol {

const protocol_number_messageConstants g_protocol_number_message_constants;

protocol_number_messageConstants::protocol_number_messageConstants() {
}

}} // namespace

