/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef protocol_keyvalue_message_CONSTANTS_H
#define protocol_keyvalue_message_CONSTANTS_H

#include "protocol_keyvalue_message_types.h"

namespace squirrel { namespace protocol {

class protocol_keyvalue_messageConstants {
 public:
  protocol_keyvalue_messageConstants();

};

extern const protocol_keyvalue_messageConstants g_protocol_keyvalue_message_constants;

}} // namespace

#endif
