/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "protocol_list_message_constants.h"

namespace squirrel { namespace protocol {

const protocol_list_messageConstants g_protocol_list_message_constants;

protocol_list_messageConstants::protocol_list_messageConstants() {
}

}} // namespace

