<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['squirrel_protocol_E_NumberRequestType'] = array(
  'NUMBER_REQUEST_TYPE_INC' => 0,
  'NUMBER_REQUEST_TYPE_DEC' => 1,
  'NUMBER_REQUEST_TYPE_RESET' => 2,
  'NUMBER_REQUEST_TYPE_DELETE' => 3,
  'NUMBER_REQUEST_TYPE_MAX' => 4,
);

final class NumberRequestType {
  const NUMBER_REQUEST_TYPE_INC = 0;
  const NUMBER_REQUEST_TYPE_DEC = 1;
  const NUMBER_REQUEST_TYPE_RESET = 2;
  const NUMBER_REQUEST_TYPE_DELETE = 3;
  const NUMBER_REQUEST_TYPE_MAX = 4;
  static public $__names = array(
    0 => 'NUMBER_REQUEST_TYPE_INC',
    1 => 'NUMBER_REQUEST_TYPE_DEC',
    2 => 'NUMBER_REQUEST_TYPE_RESET',
    3 => 'NUMBER_REQUEST_TYPE_DELETE',
    4 => 'NUMBER_REQUEST_TYPE_MAX',
  );
}

$GLOBALS['squirrel_protocol_E_NumberResponseType'] = array(
  'NUMBER_RESPONSE_TYPE_SUCCESS' => 0,
  'NUMBER_RESPONSE_TYPE_KEY_NOT_EXIST' => 1,
  'NUMBER_RESPONSE_TYPE_DISCONNECTED' => 2,
  'NUMBER_RESPONSE_TYPE_UNKNOWN' => 3,
  'NUMBER_RESPONSE_TYPE_MAX' => 4,
);

final class NumberResponseType {
  const NUMBER_RESPONSE_TYPE_SUCCESS = 0;
  const NUMBER_RESPONSE_TYPE_KEY_NOT_EXIST = 1;
  const NUMBER_RESPONSE_TYPE_DISCONNECTED = 2;
  const NUMBER_RESPONSE_TYPE_UNKNOWN = 3;
  const NUMBER_RESPONSE_TYPE_MAX = 4;
  static public $__names = array(
    0 => 'NUMBER_RESPONSE_TYPE_SUCCESS',
    1 => 'NUMBER_RESPONSE_TYPE_KEY_NOT_EXIST',
    2 => 'NUMBER_RESPONSE_TYPE_DISCONNECTED',
    3 => 'NUMBER_RESPONSE_TYPE_UNKNOWN',
    4 => 'NUMBER_RESPONSE_TYPE_MAX',
  );
}

class squirrel_protocol_NumberRequest {
  static $_TSPEC;

  public $type_ = null;
  public $key_ = null;
  public $increment_ = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'type_',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'key_',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'increment_',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['type_'])) {
        $this->type_ = $vals['type_'];
      }
      if (isset($vals['key_'])) {
        $this->key_ = $vals['key_'];
      }
      if (isset($vals['increment_'])) {
        $this->increment_ = $vals['increment_'];
      }
    }
  }

  public function getName() {
    return 'NumberRequest';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->type_);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->key_);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->increment_);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('NumberRequest');
    if ($this->type_ !== null) {
      $xfer += $output->writeFieldBegin('type_', TType::I32, 1);
      $xfer += $output->writeI32($this->type_);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->key_ !== null) {
      $xfer += $output->writeFieldBegin('key_', TType::STRING, 2);
      $xfer += $output->writeString($this->key_);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->increment_ !== null) {
      $xfer += $output->writeFieldBegin('increment_', TType::STRING, 3);
      $xfer += $output->writeString($this->increment_);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class squirrel_protocol_NumberResponse {
  static $_TSPEC;

  public $result_ = null;
  public $value_ = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'result_',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'value_',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['result_'])) {
        $this->result_ = $vals['result_'];
      }
      if (isset($vals['value_'])) {
        $this->value_ = $vals['value_'];
      }
    }
  }

  public function getName() {
    return 'NumberResponse';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->result_);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->value_);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('NumberResponse');
    if ($this->result_ !== null) {
      $xfer += $output->writeFieldBegin('result_', TType::I32, 1);
      $xfer += $output->writeI32($this->result_);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->value_ !== null) {
      $xfer += $output->writeFieldBegin('value_', TType::STRING, 2);
      $xfer += $output->writeString($this->value_);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

?>
