/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef async_request_object_CONSTANTS_H
#define async_request_object_CONSTANTS_H

#include "async_request_object_types.h"

namespace squirrel { namespace common {

class async_request_objectConstants {
 public:
  async_request_objectConstants();

};

extern const async_request_objectConstants g_async_request_object_constants;

}} // namespace

#endif
