/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "async_request_object_constants.h"

namespace squirrel { namespace common {

const async_request_objectConstants g_async_request_object_constants;

async_request_objectConstants::async_request_objectConstants() {
}

}} // namespace

