/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef keyvalue_message_CONSTANTS_H
#define keyvalue_message_CONSTANTS_H

#include "keyvalue_message_types.h"

namespace squirrel { namespace common {

class keyvalue_messageConstants {
 public:
  keyvalue_messageConstants();

};

extern const keyvalue_messageConstants g_keyvalue_message_constants;

}} // namespace

#endif
