/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "keyvalue_message_types.h"

namespace squirrel { namespace common {

int _kKeyvalueRequestTypeValues[] = {
  KeyvalueRequestType::KEYVALUE_REQUEST_TYPE_SET,
  KeyvalueRequestType::KEYVALUE_REQUEST_TYPE_GET,
  KeyvalueRequestType::KEYVALUE_REQUEST_TYPE_DELETE,
  KeyvalueRequestType::KEYVALUE_REQUEST_TYPE_SYNC_REDIS,
  KeyvalueRequestType::KEYVALUE_REQUEST_TYPE_MAX
};
const char* _kKeyvalueRequestTypeNames[] = {
  "KEYVALUE_REQUEST_TYPE_SET",
  "KEYVALUE_REQUEST_TYPE_GET",
  "KEYVALUE_REQUEST_TYPE_DELETE",
  "KEYVALUE_REQUEST_TYPE_SYNC_REDIS",
  "KEYVALUE_REQUEST_TYPE_MAX"
};
const std::map<int, const char*> _KeyvalueRequestType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kKeyvalueRequestTypeValues, _kKeyvalueRequestTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kKeyvalueResponseTypeValues[] = {
  KeyvalueResponseType::KEYVALUE_RESPONSE_TYPE_SUCCESS,
  KeyvalueResponseType::KEYVALUE_RESPONSE_TYPE_KEY_NOT_EXIST,
  KeyvalueResponseType::KEYVALUE_RESPONSE_TYPE_DISCONNECTED,
  KeyvalueResponseType::KEYVALUE_RESPONSE_TYPE_UNKNOWN,
  KeyvalueResponseType::KEYVALUE_RESPONSE_TYPE_MAX
};
const char* _kKeyvalueResponseTypeNames[] = {
  "KEYVALUE_RESPONSE_TYPE_SUCCESS",
  "KEYVALUE_RESPONSE_TYPE_KEY_NOT_EXIST",
  "KEYVALUE_RESPONSE_TYPE_DISCONNECTED",
  "KEYVALUE_RESPONSE_TYPE_UNKNOWN",
  "KEYVALUE_RESPONSE_TYPE_MAX"
};
const std::map<int, const char*> _KeyvalueResponseType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kKeyvalueResponseTypeValues, _kKeyvalueResponseTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

const char* KeyvalueRequest::ascii_fingerprint = "24652790C81ECE22B629CB60A19F1E93";
const uint8_t KeyvalueRequest::binary_fingerprint[16] = {0x24,0x65,0x27,0x90,0xC8,0x1E,0xCE,0x22,0xB6,0x29,0xCB,0x60,0xA1,0x9F,0x1E,0x93};

uint32_t KeyvalueRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_type_ = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->type_ = (KeyvalueRequestType::type)ecast0;
          isset_type_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->value_);
          this->__isset.value_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_type_)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t KeyvalueRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("KeyvalueRequest");
  xfer += oprot->writeFieldBegin("type_", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->type_);
  xfer += oprot->writeFieldEnd();
  if (this->__isset.value_) {
    xfer += oprot->writeFieldBegin("value_", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeBinary(this->value_);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

const char* KeyvalueResponse::ascii_fingerprint = "19AAB18E981C4EB11AEBB34F40FF0939";
const uint8_t KeyvalueResponse::binary_fingerprint[16] = {0x19,0xAA,0xB1,0x8E,0x98,0x1C,0x4E,0xB1,0x1A,0xEB,0xB3,0x4F,0x40,0xFF,0x09,0x39};

uint32_t KeyvalueResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_type_ = false;
  bool isset_result_ = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast1;
          xfer += iprot->readI32(ecast1);
          this->type_ = (KeyvalueRequestType::type)ecast1;
          isset_type_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast2;
          xfer += iprot->readI32(ecast2);
          this->result_ = (KeyvalueResponseType::type)ecast2;
          isset_result_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readBinary(this->value_);
          this->__isset.value_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_type_)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_result_)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t KeyvalueResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("KeyvalueResponse");
  xfer += oprot->writeFieldBegin("type_", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32((int32_t)this->type_);
  xfer += oprot->writeFieldEnd();
  xfer += oprot->writeFieldBegin("result_", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32((int32_t)this->result_);
  xfer += oprot->writeFieldEnd();
  if (this->__isset.value_) {
    xfer += oprot->writeFieldBegin("value_", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeBinary(this->value_);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

}} // namespace
