/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "keyvalue_message_constants.h"

namespace squirrel { namespace common {

const keyvalue_messageConstants g_keyvalue_message_constants;

keyvalue_messageConstants::keyvalue_messageConstants() {
}

}} // namespace

