/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef list_message_CONSTANTS_H
#define list_message_CONSTANTS_H

#include "list_message_types.h"

namespace squirrel { namespace common {

class list_messageConstants {
 public:
  list_messageConstants();

};

extern const list_messageConstants g_list_message_constants;

}} // namespace

#endif
