/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "list_message_constants.h"

namespace squirrel { namespace common {

const list_messageConstants g_list_message_constants;

list_messageConstants::list_messageConstants() {
}

}} // namespace

