/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef map_message_CONSTANTS_H
#define map_message_CONSTANTS_H

#include "map_message_types.h"

namespace squirrel { namespace common {

class map_messageConstants {
 public:
  map_messageConstants();

};

extern const map_messageConstants g_map_message_constants;

}} // namespace

#endif
