/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "map_message_constants.h"

namespace squirrel { namespace common {

const map_messageConstants g_map_message_constants;

map_messageConstants::map_messageConstants() {
}

}} // namespace

