/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef message_data_proxy_CONSTANTS_H
#define message_data_proxy_CONSTANTS_H

#include "message_data_proxy_types.h"

namespace squirrel { namespace common {

class message_data_proxyConstants {
 public:
  message_data_proxyConstants();

};

extern const message_data_proxyConstants g_message_data_proxy_constants;

}} // namespace

#endif
