/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "message_schedule_constants.h"

namespace squirrel { namespace common {

const message_scheduleConstants g_message_schedule_constants;

message_scheduleConstants::message_scheduleConstants() {
}

}} // namespace

