/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "message_data_proxy_constants.h"

namespace squirrel { namespace common {

const message_data_proxyConstants g_message_data_proxy_constants;

message_data_proxyConstants::message_data_proxyConstants() {
}

}} // namespace

