/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef message_schedule_CONSTANTS_H
#define message_schedule_CONSTANTS_H

#include "message_schedule_types.h"

namespace squirrel { namespace common {

class message_scheduleConstants {
 public:
  message_scheduleConstants();

};

extern const message_scheduleConstants g_message_schedule_constants;

}} // namespace

#endif
