/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "number_message_constants.h"

namespace squirrel { namespace common {

const number_messageConstants g_number_message_constants;

number_messageConstants::number_messageConstants() {
}

}} // namespace

