/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef number_message_CONSTANTS_H
#define number_message_CONSTANTS_H

#include "number_message_types.h"

namespace squirrel { namespace common {

class number_messageConstants {
 public:
  number_messageConstants();

};

extern const number_messageConstants g_number_message_constants;

}} // namespace

#endif
