/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef request_type_CONSTANTS_H
#define request_type_CONSTANTS_H

#include "request_type_types.h"

namespace squirrel { namespace common {

class request_typeConstants {
 public:
  request_typeConstants();

};

extern const request_typeConstants g_request_type_constants;

}} // namespace

#endif
