/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "request_type_constants.h"

namespace squirrel { namespace common {

const request_typeConstants g_request_type_constants;

request_typeConstants::request_typeConstants() {
}

}} // namespace

