/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "request_type_types.h"

namespace squirrel { namespace common {

int _kRequestTypeValues[] = {
  RequestType::REQUEST_TYPE_KEYVALUE,
  RequestType::REQUEST_TYPE_NUMBER,
  RequestType::REQUEST_TYPE_LIST,
  RequestType::REQUEST_TYPE_MAP,
  RequestType::REQUEST_TYPE_MAX
};
const char* _kRequestTypeNames[] = {
  "REQUEST_TYPE_KEYVALUE",
  "REQUEST_TYPE_NUMBER",
  "REQUEST_TYPE_LIST",
  "REQUEST_TYPE_MAP",
  "REQUEST_TYPE_MAX"
};
const std::map<int, const char*> _RequestType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(5, _kRequestTypeValues, _kRequestTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kStorageTypeValues[] = {
  StorageType::STORAGE_TYPE_CACHE,
  StorageType::STORAGE_TYPE_DISK
};
const char* _kStorageTypeNames[] = {
  "STORAGE_TYPE_CACHE",
  "STORAGE_TYPE_DISK"
};
const std::map<int, const char*> _StorageType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(2, _kStorageTypeValues, _kStorageTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

}} // namespace
