/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_type_CONSTANTS_H
#define server_type_CONSTANTS_H

#include "server_type_types.h"

namespace squirrel { namespace common {

class server_typeConstants {
 public:
  server_typeConstants();

};

extern const server_typeConstants g_server_type_constants;

}} // namespace

#endif
